# -*- coding: utf-8 -*-
{
    'name': 'HeatMe : Accounting',
    'version': '16.0.1.0.0',
    'author': 'Aziz, Netskill Group(NSG)',
    'category': 'Accounting',
    'summary': 'Accounting Management',
    'website': 'https://netskill.be/',
    "depends": ["account", "hm_sale", "hm_sale_management", "account_followup"],
    "data": [
        "data/ir_actions_server.xml",
        "data/base_automation.xml",
        "data/data_account_payment_mode.xml",
        "data/mail_invoice_template.xml",
        "security/account_security.xml",
        "security/ir.model.access.csv",
        "views/account_move_view.xml",
        "views/account_views.xml",
        "views/res_bank_view.xml",
        "views/account_payment_view.xml",
        "views/account_menu.xml",
        "views/res_partner_views.xml",
        "views/report_invoice.xml",
        "views/report_followup.xml",
        "wizard/account_payment_register_views.xml",
    ],
    "installable": True,
    "application": True,
    'license': 'LGPL-3',
}
