# -*- coding: utf-8 -*-
{
    'name': 'HeatMe : Sales Technician',
    'version': '16.0.1.0.0',
    'author': 'Aziz, Netskill Group(NSG)',
    'category': 'Sales',
    'summary': 'Sales Management',
    'website': 'https://netskill.be/',
    'depends': ['hm_base_setup', 'sale_management'],
    'data': [
        'security/ir.model.access.csv',
        'data/ir_rule.xml',
        'data/ir_cron_maintenance.xml',
        'data/ir_cron.xml',
        'views/hm_agreement_view.xml',
        'views/product_template_view.xml',
        'views/hm_work_type.xml',
        'views/res_partner.xml',
        'views/agreement_region.xml',
        'views/sale_order.xml',
        'views/technicien_choice_view.xml',
        'views/category_competence_view.xml',
        'views/customer_availability_view.xml',
        'views/intervention_proposal_view.xml',
        "views/technician_views.xml",
        "views/sale_order_template_views.xml",

        'wizard/availability_popup_view.xml',
        'wizard/hm_proposal_warning_wizard_view.xml',
    ],
    'installable': True,
    'application': True,
    'license': 'LGPL-3',
}
