# -*- coding: utf-8 -*-
{
    'name': 'HeatMe : Base',
    'version': '16.0.1.0.0',
    'author': 'Aziz, Netskill Group(NSG)',
    'category': 'Base/Technical',
    'summary': 'The kernel of HeatMe Management',
    'website': 'https://netskill.be/',
    "depends": ["base", "base_geolocalize", "sale", "purchase", "helpdesk_sale", "mail"],
    "data": [
        "data/technician_availability_data.xml",
        "data/mail_template.xml",
        "security/ir.model.access.csv",
        "data/ir_actions_server.xml",
        "data/base_automation.xml",
        "data/customer_source_data.xml",
        "views/res_lang_views.xml",
        "views/base_menu.xml",
        "views/access_profession_views.xml",
        "views/res_partner_views.xml",
        "views/res_users_views.xml",
        "views/marque_chaudiere_views.xml",
        "views/spoken_language_views.xml",
        "views/zip_code_views.xml",
        "views/res_country_views.xml",
        "views/res_groups_views.xml",
        "views/report_document.xml",
        "views/mail_mail_views.xml",
        "views/helpdesk_views.xml",
    ],
    'installable': True,
    'application': True,
    'license': 'LGPL-3',
}
