# -*- coding: utf-8 -*-
{
    'name': 'HeatMe : Sales',
    'version': '16.0.1.0.0',
    'author': 'Aziz, Netskill Group(NSG)',
    'category': 'Sales',
    'summary': 'Sales Management',
    'website': 'https://netskill.be/',
    'depends': [
        'sale',
        'sale_crm',
        'hm_purchase_sale_budget',
        'hm_primes',
    ],
    'data': [
        'data/mail_template.xml',
        'data/technical_base_automation.xml',
        'data/ir_actions_server.xml',
        'data/base_automation.xml',
        'data/ir_cron.xml',
        'security/sale_security.xml',
        'security/ir.model.access.csv',
        'security/sms_security.xml',
        'security/groups.xml',
        'views/emergency_degrees_view.xml',
        'views/sale_views.xml',
        'views/sale_report.xml',
        'views/sale_portal_templates.xml',
        'views/report_sale_order.xml',
        'views/report_technician_work_order.xml',
        'views/report_quote_order_without_price.xml',
        'views/report_proposal_radiators_with_price.xml',
        'views/report_proposal_radiators_without_price.xml',
        'views/report_work_report.xml',
        'views/sale_report_views.xml',
        'views/sale_order_menu.xml',
        'views/sale_order_line.xml',
        'views/resource_calendar_view.xml',
        'views/res_partner_view.xml',
    ],
    'assets': {
        'web.assets_backend': [
            'hm_sale/static/src/js/custom_product_discount_field.js',
            'hm_sale/static/src/js/show_description_widget.js',
            'hm_sale/static/src/xml/templates.xml',
            'hm_sale/static/src/css/style.css',
        ],
    },
    'installable': True,
    'application': True,
    'license': 'LGPL-3',
}
